<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExerciceByStrategieAndPartie($strategie, $partie)
    {
        $em = $this
            ->getEntityManager();
        $queryExercice = $em->createQuery(
            'SELECT e.idExercice
            FROM UPONDOrthophonieBundle:Exercice e
            WHERE e.partie = :partie AND e.strategie = :strategie'
        );
        $queryExercice->setParameters(array('strategie' => $strategie,
            'partie' => $partie));

        $idExercice = $queryExercice->getSingleResult();

        $repositoryExercice = $em
            ->getRepository('UPONDOrthophonieBundle:Exercice')
        ;

        // on récupere l'entité de l'ID
        $exercice = $repositoryExercice->findOneByIdExercice($idExercice);
        return $exercice;
    }

}
