<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * MultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaRepository extends \Doctrine\ORM\EntityRepository
{
}
