<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByNomEtPrenom($NomPrenom)
    {
        $em = $this
            ->getEntityManager();
        // on récupere l'entité de l'ID
        $query = $em->createQuery(
            "SELECT p
                FROM UPONDOrthophonieBundle:Patient p
                JOIN p.utilisateur u
                WHERE CONCAT(u.nom, CONCAT(' ',u.prenom)) = :NomPrenom"
        );
        $query->setParameter('NomPrenom', $NomPrenom);
        $patient = $query->getOneOrNullResult();
        return $patient;
    }
    public function findByPatientListByNomPrenom (){
        $em=$this
            ->getEntityManager();

        $em = $this
            ->getEntityManager();
        // on récupere l'entité de l'ID
        $query = $em->createQuery(
            "SELECT p.idPatient, u.nom, u.prenom  
                FROM UPONDOrthophonieBundle:Patient p
                JOIN p.utilisateur u"
        );
        
        $patient = $query->getResult();
        return $patient;
    }
    public function findUnaffectedPatient(){
        $em = $this
            ->getEntityManager();

        $query = $em->createQuery(
            "SELECT p
             FROM UPONDOrthophonieBundle:Patient p
             LEFT JOIN p.medecins m"
        );
        $patient=$query->getResult();
        return $patient;
    }

    
}
