<?php

namespace UPOND\OrthophonieBundle\Repository;

/**
 * PauseVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PauseVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
