upond_orthophonie_home:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Phases:index }

upond_orthophonie_invite:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Invite:accueil }

upond_orthophonie_createExercice:
    path:     /select_partie/{phase}/{niveau}/{strategie}
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie }

upond_orthophonie_entrainement_niveau2:
    path:     /select_partie_entrainement_niveau2
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , phase: "Entrainement", niveau: 2, strategie: "Aléatoire"}

upond_orthophonie_transfert:
    path:      /select_partie_transfert
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , phase: "Transfert" , niveau: 0, strategie: "Aléatoire"}

upond_orthophonie_morphologie:
    path:     /select_partie_metier
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , strategie: "Métier"}

upond_orthophonie_morphologie_inverse:
    path:     /select_partie_morphologie
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , strategie: "Morphologie inverse"}

upond_orthophonie_metier:
    path:     /select_partie_morphologie_inverse
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , strategie: "Métier"}

upond_orthophonie_association_idees:
    path:     /select_partie_association_idees
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie , strategie: "Association d'idées"}

upond_orthophonie_stats:
    path:     /stats
    defaults: { _controller: UPONDOrthophonieBundle:Phases:stats }

upond_orthophonie_phases:
    path:     /phases
    defaults: { _controller: UPONDOrthophonieBundle:Phases:phases }

upond_orthophonie_exercice:
    path:     /exercice
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:afficherExercice }

upond_orthophonie_start:
    path:     /start
    defaults: { _controller: UPONDOrthophonieBundle:Partie:start }

upond_orthophonie_stats:
    path:      /statistiques
    defaults:  { _controller: UPONDOrthophonieBundle:Statistique:statistique }

upond_orthophonie_administration_patient:
    path:      /patients
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:patients }

upond_orthophonie_administration_medecin:
    path:      /medecins
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:medecins }

upond_orthophonie_administration_exercice:
    path:      /exercices
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:exercices }