upond_orthophonie_home:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Phases:index }

upond_orthophonie_invite:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Invite:accueil }

upond_orthophonie_createExercice:
    path:     /select_partie/{phase}/{niveau}/{strategie}
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:selectPartie }

upond_orthophonie_stats:
    path:     /stats
    defaults: { _controller: UPONDOrthophonieBundle:Phases:stats }

upond_orthophonie_phases:
    path:     /phases
    defaults: { _controller: UPONDOrthophonieBundle:Phases:phases }

upond_orthophonie_exercice:
    path:     /exercice
    defaults: { _controller: UPONDOrthophonieBundle:Exercice:afficherExercice }

upond_orthophonie_start:
    path:     /start
    defaults: { _controller: UPONDOrthophonieBundle:Partie:start }

upond_orthophonie_stats:
    path:      /statistiques
    defaults:  { _controller: UPONDOrthophonieBundle:Statistique:statistique }

upond_orthophonie_administration_patient:
    path:      /patients
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:patients }

upond_orthophonie_administration_medecin:
    path:      /medecins
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:medecins }

upond_orthophonie_administration_exercice:
    path:      /exercices
    defaults:  { _controller: UPONDOrthophonieBundle:Administration:exercices }