upond_orthophonie_home:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Phases:index }

upond_orthophonie_invite:
    path:     /
    defaults: { _controller: UPONDOrthophonieBundle:Invite:accueil }

upond_orthophonie_strategie:
    path:     /st
    defaults: { _controller: UPONDOrthophonieBundle:Phases:st }

upond_orthophonie_stats:
    path:     /stats
    defaults: { _controller: UPONDOrthophonieBundle:Phases:stats }

upond_orthophonie_phases:
    path:     /phases
    defaults: { _controller: UPONDOrthophonieBundle:Phases:phases }

upond_orthophonie_exercice:
    path:     /exercice
    defaults: { _controller: UPONDOrthophonieBundle:Phases:exercice }

upond_orthophonie_start:
    path:     /start
    defaults: { _controller: UPONDOrthophonieBundle:Partie:start }

upond_orthophonie_apprentissage:
    path:      /apprentissage
    defaults:  { _controller: UPONDOrthophonieBundle:Phases:apprentissage }

upond_orthophonie_entrainement:
    path:      /entrainement
    defaults:  { _controller: UPONDOrthophonieBundle:Phases:entrainement }

upond_orthophonie_transfert:
    path:      /transfert
    defaults:  { _controller: UPONDOrthophonieBundle:Phases:transfert }